const ERROR_CODE = Object.freeze({
  OTHER: 'OTR',
  NOT_MY_TURN: 'NMY',
  LOBBY_NOT_FOUND: 'LNF',
  USER_IS_OFFLINE: 'UIO',
  PLAYER_LEFT_GAME: 'PLG',
  PLAYER_NOT_FOUND: 'PNF',
  SOCKET_TERMINATED: 'ST',
  GAME_ALREADY_FULL: 'GAF',
  LOBBY_LIMIT_REACHED: 'LLR',
  MOVE_IN_INVALID_CELL: 'MIIC',
  MOVE_IN_FINISHED_GAME: 'MIFG',
  ANOTHER_REQUEST_PENDING: 'ARP',
  SWITCH_LOBBY_REQUEST_NOT_VALID: 'SLRNV',
  SWITCHED_LOBBY_SAME_AS_ORIGINAL: 'SLSO',
  CAN_NOT_LEAVE_GAME_IN_PROGRESS: 'CNLGIP',
});

export { ERROR_CODE };
