import { GameState } from './game';
import type {
  ILobbyData,
  ISocketData,
  IPlayerState,
  PlayerSymbol,
  IExtendedSocket,
  GameWinnerState,
  IConnectionState,
  ISocketKnownError,
  IExtendedPlayerState,
  // SOCKET
  ISocketMoveData,
  ISwitchRequestData,
  ISocketJoinAckData,
  ISocketMoveAckData,
  ISocketOpenAckData,
  ISocketCloseAckData,
  ISocketGameStateData,
  ISocketLeaveLobbyData,
  ISocketGameStateAckData,
  ISocketLeaveLobbyAckData,
  ISocketSwitchLobbyRequestAckData,
  ISocketSwitchLobbyResponseAckData,
} from './types';
import { ERROR_CODE } from './error-codes';
import {
  USER_ID_LEN,
  LOBBY_ID_LEN,
  LOCAL_PLAYER_ID,
  HEARTBEAT_VALUE,
  HEARTBEAT_OFFSET,
  REQUEST_DURATION,
  ONLINE_PLAYER_ID,
  HEARTBEAT_INTERVAL,
  REQUEST_BUFFER_DURATION,
} from './constants';

export {
  GameState,
  ERROR_CODE,
  USER_ID_LEN,
  LOBBY_ID_LEN,
  LOCAL_PLAYER_ID,
  HEARTBEAT_VALUE,
  HEARTBEAT_OFFSET,
  ONLINE_PLAYER_ID,
  REQUEST_DURATION,
  HEARTBEAT_INTERVAL,
  REQUEST_BUFFER_DURATION,
  type ILobbyData,
  type ISocketData,
  type PlayerSymbol,
  type IPlayerState,
  type GameWinnerState,
  type IExtendedSocket,
  type IConnectionState,
  type IExtendedPlayerState,
  // SOCKET
  type ISocketMoveData,
  type ISocketKnownError,
  type ISocketMoveAckData,
  type ISwitchRequestData,
  type ISocketOpenAckData,
  type ISocketJoinAckData,
  type ISocketCloseAckData,
  type ISocketGameStateData,
  type ISocketLeaveLobbyData,
  type ISocketGameStateAckData,
  type ISocketLeaveLobbyAckData,
  type ISocketSwitchLobbyRequestAckData,
  type ISocketSwitchLobbyResponseAckData,
};
